### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gilles-bertrand** [Rastopyr/ember-cli-fabric2-shim#2]
Could you give an example  of how integrating it?
It would be great :)

**Comment by Rastopyr** [comment]
Hey @gilles-bertrand! Firstly you should install this addon like each another addon:
`ember install ember-cli-fabric2-shim`.

Then you can import fabric object like in this section:
[How to use](https://github.com/Rastopyr/ember-cli-fabric2-shim#how-to-use)

**Comment by Rastopyr** [comment]
Or you mean something else? How to integrate this with Ember.js components?

**Comment by Rastopyr** [comment]
ember-cli-fabric2-shim is deprecated in favor of https://github.com/ef4/ember-auto-import or https://github.com/rwjblue/ember-cli-cjs-transform
