### ISSUE TITLE
How can I update fabric.js file?

### ISSUE THREAD

**Issue by fredguth** [Rastopyr/ember-cli-fabric2-shim#3]
Fabricjs is in 2.2, I understand this add-on uses the beta. How should I upgrade?

**Comment by Rastopyr** [comment]
Hey @fredguth! 

I think is best solution will be link this repo with https://github.com/kangax/fabric.js. But i can do it at this weekends.

**Comment by fredguth** [comment]
Have you had any chance to take a look? Can I help somehow?

**Comment by Rastopyr** [comment]
Hey, sorry for long await, i will fix this issue in 2-3 days

**Comment by Rastopyr** [comment]
@fredguth i will push new version to https://github.com/Rastopyr/ember-cli-fabricjs-shim
